---
title: "Reshaping and Joining Data in R with dplyr"
---

This is the website for the workshop "Reshaping and Joining Data in R with dplyr" offered by JHU Sheridan Libraries Data Services every semester.

The `dplyr` package is a popular R package that people often use to manipulate and join datasets. Join JHU Data Services for this workshop and you will learn to use several functions, including  `mutate()`,  `filter()`,  `select()`,  `summarize()` and  `group_by()`, in dplyr to manipulate data for the first half of the workshop. For the second part of this workshop, you will learn the join functions (e.g.  `left_join()`,  `right_join()`,  `inner_join()`,  `semi_join()`,  `anti_join()`,  `full_join()`,  `bind_rows()` and `bind_cols()`) and set operations (e.g. `union()`, `intersect()` and `setdiff()`) in dplyr to combine two datasets.

-   **Survey:** Please be sure to take our [survey](https://bit.ly/dplyr-survey) and let us know your feedback about our March 11th, 2025 "Reshaping and Joining Data in R with dplyr" session.

-   **Slides**: The slides are available [here](https://jhu-data-services.github.io/dplyr-quarto-site/Manipulating%20and%20Joining%20Data%20in%20R%20with%20dplyr.html) (or above using the `Presentation` link).

-   **Recording**: This session was not recorded, but you can view a prior recording of this session [here](https://jh.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ceb104a6-09de-41dd-9008-b20a014711b1).

## dplyr Resources

-   R for Data Science 2e, Chapters [3](https://r4ds.hadley.nz/data-transform) & [19](https://r4ds.hadley.nz/joins)

-   [dplyr documentation](https://dplyr.tidyverse.org/index.html)

-   [Software Carpentries: Data Frame Manipulation with dplyr](https://swcarpentry.github.io/r-novice-gapminder/13-dplyr.html)
